
# R Markdown Assignment
*Yusuf ISIK* *7 August 2020*

In 2019, I graduated from Istanbul Technical University (ITU). Currently working at ITU as Teaching Assistant. I become interested in the areas of Data Mining and Business Intelligence in the last year of my undergraduate education while writing down graduation thesis. Now I would like to be more qualified in Data Analysis. 

[LinkedIn](https://www.linkedin.com/in/isikyusuf/)

# UseR! 2020 
I would like to mention one of the videos in the channel which has longer videos than previous year. In the talk, six people from different backgrounds(diversified) introduced themselves and described their relations with R. One of the story of them was outstanding. An Argentinian woman living in a rural area in Argentina and has no easy access to center of the city. She then started teaching Spanish and with that financing she was able to enroll master degree in Data Mining. 
[Supporting diversity in the R community (R forwards panel)](https://www.youtube.com/watch?v=gDO1OphmF5Q)
# Doing Journalism with R (B. Witzenberger)
Is it possible to do Journalism with R? In this video the lecturer tells how they are doing it. 
He describes data journalism as story telling with data in a fast changing data driven world. 
Today people do not have time to read detailed reports, journalists have to use outstanding tools to catch the attention. 
The newspaper the lecturer work for has a team to make data projects in the long and short terms. 
As short term projects they analyse election results and political debates. On the other hand, long term projects includes large scale investigations (Panama Papers, parliement speeches).  
Data journalists has similar work process as regular ones. Here is the steps: find the suitable data, tidy, analyse and visualize with R. 
They use public data, some scraped data or leaked data as data resources. 
Focusing on story points (winners/losers, outliers, change over time) is useful to attract readers. 

[Doing Journalism with R](https://www.youtube.com/watch?v=1bmdHy5vtfY)



